
- hosts: master-leader
  gather_facts: false
  vars_files:
  - vars/global.yaml

  tasks:

  - include_tasks: "tasks/k8s-api-localhost-alias.yaml"

  - name: add tmp dir for kubeadm config
    tempfile: state=directory
    register: tempdir
    tags:
    - kubeadm-config

  - name: template kubeadm-config.yaml
    template: src=templates/kubeadm-config.yaml.j2 dest={{ tempdir.path }}/kubeadm-config.yaml
    tags:
    - kubeadm-config

  - name: init k8s cluster
    shell: kubeadm init --config={{ tempdir.path }}/kubeadm-config.yaml --upload-certs

  - name: template canal.yaml
    template: src=templates/canal-{{ canal_version | default("3.9") }}.yaml.j2 dest={{ tempdir.path }}/canal.yaml

  - name: apply canal cni
    shell: kubectl apply -f {{tempdir.path }}/canal.yaml
    environment: 
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: rm cloud.cfg tmp dir
    file: path={{ tempdir.path}} state=absent

  - include_tasks: "tasks/wait-node-ready-state.yaml"


