---

- name: make nginx directory
  file:
    path: /etc/nginx
    state: directory
    mode: 0700
    owner: root

- name: template nginx-proxy configuration
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    mode: 0755
    backup: yes

- name: get checksum from nginx-config
  stat:
    path: "/etc/nginx/nginx.conf"
  register: nginx_stat

- name: template nginx static pod manifest
  template:
    src: templates/nginx-proxy-manifest.yaml.j2
    dest: "/etc/kubernetes/manifest/nginx-proxy.yaml"

